namespace: network
name: nios
version: 0.0.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [private]
# NOTE: No more dependencies can be added to this list
dependencies:
  ansible.netcommon: '>=1.0.0'

